data_augmentation:
  hsv_noise: [15,15,15]
  bright_mag: [0.5,1.5]
  gaussian_noise:
    rgb: 2
    depth: 5
  gaussian_blur_kernel: 6
  depth_missing_percent: 0.4

learning_rate: 0.001
weight_decay: 0.000001
epochs: 300
loss_weights:
  trans: 1
  rot: 1

data_path: /media/bowen/e25c9489-2f57-42dd-b076-021c59369fec/github/end_to_end_tracking/Experiments/master_chef_can/train_data_blender_DR
validation_path: /media/bowen/e25c9489-2f57-42dd-b076-021c59369fec/github/end_to_end_tracking/Experiments/master_chef_can/validation_data_blender_DR
batch_size: 200
n_workers: 20